version: '3'
services:
  web:
    image: flask-app:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "sqlite:////home/guy/Desktop/pro1/users.db"
    volumes:
      - ./data:/home/guy/Desktop/pro1/
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
